config/routes.rb
Rails.application.routes.draw do
  namespace :portal, path: '/' do
    root 'top#index'
    get 'signup' => 'accounts#signup', as: :signup
    resources :accounts, only: [ :new, :create ] do
      patch :send_mail, on: :collection
      get :after_send, on: :collection
      get :thanks, on: :collection
    end
  end
  namespace :customer do
    root 'articles#index', as: :root
    get 'login' => 'sessions#new', as: :login
    resource :session, only: [ :create, :destroy ]
    resource :forgot_password, only: [ :new, :create ] do
      get :after_send
      patch :change_password
    end
    get 'input_password' => 'forgot_passwords#input_password'
    resources :articles
  end
  namespace :admin do
    root 'dashboard#index', as: :root
    get 'login' => 'sessions#new', as: :login
    resource :session, only: [ :create, :destroy ]
    resources :articles
    get 'input_url' => 'articles#input_url'
    post 'scrape_url' => 'articles#scrape_url'
    resources :categories
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :text(65535)      not null
#  sort_order :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_many :articles
  validates :name, uniqueness: true
  validates :sort_order, uniqueness: true

  def last_sort_order
    if Category.exists?
      last_category = Category.order(sort_order: :asc).last
      last_category.sort_order + 1
    else
      1
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::Base
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(create_category_params)
    @category.sort_order = @category.last_sort_order
    if @category.save
      flash.notice = 'カテゴリを登録しました'
      redirect_to :admin_categories
    else
      flash.now[:alert] = 'カテゴリの登録に失敗しました'
      render action: 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.assign_attributes(update_category_params)
    if @category.save
      flash.notice = 'カテゴリを更新しました'
      redirect_to :admin_categories
    else
      flash.now[:alert] = 'カテゴリの更新に失敗しました'
      render action: 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash.notice = 'カテゴリを削除しました'
    else
      flash.alert = 'カテゴリの削除に失敗しました'
    end
    redirect_to :admin_categories
  end

  private
  def create_category_params
    params.require(:category).permit(:name)
  end

  def update_category_params
    params.require(:category).permit(:name, :sort_order)
  end
end

app/views/admin/categories/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>カテゴリ名</th>
      <th>表示の順番</th>
      <th>アクション</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
        <td><%= c.sort_order %></td>
        <td>
          <%= link_to '編集', edit_admin_category_path(c) %>
          <%= link_to '削除', "/admin/categories/#{c.id}", method: :delete,
            data: { confirm: '本当に削除してよろしいですか？この操作は取り消せません'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/edit.html.erb
<% @title = 'カテゴリ編集' %>
<h2><%= @title %></h2>

<%= form_for @category, :url => {:controller => :categories, :action => :update} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :sort_order %>
    <%= f.text_field :sort_order %>
  </div>
  <%= f.submit 'カテゴリを更新' %>
<% end %>

app/views/admin/categories/index.html.erb
<% @title = 'カテゴリ一覧' %>
<h2><%= @title %></h2>

<%= link_to 'カテゴリを作成する', :new_admin_category, class: 'btn btn-info' %>

<div>
  <%= render 'table' %>
</div>

app/views/admin/categories/new.html.erb
<% @title = 'カテゴリ作成' %>
<h2><%= @title %></h2>

<%= form_for @category, url: '/admin/categories' do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'カテゴリを作成' %>
<% end %>